apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bvvd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0021-tenant/ci1t-830-0021-app/devfile-sample-bvvd@sha256:d5dfce40b2f1bcdd6dca7050f562da4ff9abebf2f4b318ff987193db9c106e62
        name: my-nodejs
        resources: {}
status: {}
